In [1]:
import cv2
import os
import matplotlib.pyplot as plt
import math
import numpy as np

from glob import glob

from src.image_processor import ImageProcessor

# Roteiro I

In [4]:
input_directory = 'data/bracs-binary/train'
output_directory = './bracs-binary_features/o1_o2'

processor = ImageProcessor(input_directory)
processor.load_images()

# Extração e salvamento das features O1, O2 na pasta especificada
processor.gen_o1_o2(output_directory)

# Roteiro II

In [6]:
file_path = "./bracs-binary_features/o1_o2/o1_o2_BRACS_1643_N_13_original.npy"
data = np.load(file_path)
print(data.shape())

[[136 136 139 ... 138 132 132]
 [136 135 136 ... 133 147 151]
 [137 138 137 ... 157 161 151]
 ...
 [146 144 138 ... 149 150 148]
 [135 134 134 ... 158 147 153]
 [136 130 129 ... 130 131 131]]


# Roteiro III